import cv2 
image = cv2.imread(r"C:\Users\Nadesa Krishnan\OneDrive\Pictures\MS Dhon wal.png")
gray_scale=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
print("original image dimension:")
print("height",image.shape[0])
print("width",image.shape[1])
print("channel",image.shape[2])
print("gray scale dimension:")
print("height",gray_scale.shape[0])
print("width",gray_scale.shape[1])
print("channel:")
cv2.imshow("gray_scale Image", gray_scale) 
cv2.waitKey(0)
cv2.destroyAllWindows()